version: '3.8'

services:
  app:
    image: order-service-image
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/orders_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Ld274131511

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Ld274131511
      MYSQL_DATABASE: orders_db
      # MYSQL_USER: root
      # MYSQL_PASSWORD: Ld274131511
    ports:
      - "3306:3306"
